mod_loader=fabric
fabric_loader_dependency=>=0.16.9
modmenu_version=13.0.0-beta.1
minecraft_dependency=1.21.1

# Fabric API
import_fabric_api=false
# fabric_api_version=0.110.5+1.21.4

# Optional dependencies
curseforge_upload_optional_dependencies=modmenu, cloth-config
modrinth_upload_optional_dependencies=modmenu, cloth-config
