apply plugin: 'com.gradleup.shadow'
apply plugin: 'fabric-loom'

apply from: "https://raw.githubusercontent.com/theLeialoha/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

repositories {
    maven { url = 'https://maven.shedaniel.me/' }
}

dependencies {
    compileOnly ("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: 'net.fabricmc:fabric-loader')
        exclude(group: 'net.fabricmc.fabric-api')
    }
}

tasks.register('prepareWorkspace') {

}
